<?php
declare(strict_types=1);
require_once __DIR__.'/includes/session_org.php';require_once __DIR__.'/includes/org_context.php';require_once __DIR__.'/includes/org_manager_guard.php';require_once __DIR__.'/includes/org_ecommerce.php';
org_require_manager();org_require_commerce_seller();$dangerZoneEmbedded=!empty($dangerZoneEmbedded);if(!$dangerZoneEmbedded){$pageTitle='Danger Zone';require_once __DIR__.'/includes/org_page_shell.php';org_page_shell_open($pageTitle,'<link rel="stylesheet" href="css/commerce-hub.css?v=17">');org_page_body_open('commerce-page');}
$dangerItems=[
 ['fa-trash-o','Delete Store','Permanently delete your store and all of its data. This action cannot be undone.',['Your store profile and settings','All products, orders, customers, and reviews','All data, reports, and analytics'],'Delete Store','DELETE STORE'],
 ['fa-user-o','Remove Staff Access',"Permanently remove a staff member's access to your store.",['The staff member will no longer be able to access the store','This action does not delete their account','You can re-invite them later if needed'],'Manage Staff Access',''],
 ['fa-download','Export Store Data','Download a copy of your store data. We will email you a secure link once your export is ready.',['Includes products, orders, customers, and settings','May take a few minutes to prepare','Available for 7 days after export'],'Export Data',''],
 ['fa-undo','Reset Store Settings','Reset your store settings to default. This action cannot be undone.',['All store settings will be reset to default values','Your products, orders, and customers will not be affected','You will need to reconfigure your settings'],'Reset Settings','RESET'],
 ['fa-times','Close Store',"Temporarily close your store. Customers won't be able to place new orders.",['Your store will be hidden from customers','Existing orders and data will be preserved','You can reopen your store at any time'],'Close Store',''],
];
?>
<style>.dz{--t:#10204a;--m:#687593;--r:#ed1c24;--b:#ffc9cc;color:var(--t);height:calc(100vh - var(--org-header-h,48px) - 34px);display:flex;flex-direction:column;gap:7px;overflow:hidden}.dz *{box-sizing:border-box}.dz-head{display:flex;justify-content:space-between}.dz h1{font-size:21px;margin:0}.dz-crumb,.dz-sub{font-size:8px;font-weight:700;margin:0 0 2px}.dz-crumb a{color:#143dff;text-decoration:none}.dz-sub{color:var(--m)}.dz-save{height:30px;border:0;border-radius:6px;background:#143dff;color:#fff;padding:0 14px;font-size:9px;font-weight:800}.dz-body{display:grid;grid-template-columns:155px 1fr;gap:7px;flex:1;min-height:0}.dz-nav{border:1px solid #dce5f1;border-radius:8px;background:var(--ch-surface,#fff);padding:5px}.dz-tab{display:flex;align-items:center;width:100%;height:31px;padding:0 8px;border-radius:6px;color:var(--t);font-size:8px;font-weight:800;text-decoration:none}.dz-tab i{width:20px;font-size:12px}.dz-tab.on{background:#fff1f2;color:var(--r);border-left:2px solid var(--r)}.dz-tab.danger{color:var(--r)}.dz-main{display:grid;grid-template-rows:repeat(5,1fr) 39px;gap:7px;min-height:0}.dz-card{display:grid;grid-template-columns:64px 1fr 205px;align-items:center;border:1px solid var(--b);border-radius:8px;background:var(--ch-surface,#fff);padding:8px 14px;min-height:0}.dz-icon{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:#fff0f1;color:var(--r);font-size:23px}.dz-copy h2{font-size:10px;color:#c9151d;margin:0 0 4px}.dz-copy p,.dz-copy li{font-size:7px;margin:0;color:var(--t)}.dz-copy ul{margin:5px 0 0;padding-left:14px;line-height:1.65}.dz-action{display:flex;flex-direction:column;align-items:flex-start;gap:7px}.dz-action button{min-width:104px;height:29px;border:1px solid #ff6e75;border-radius:5px;background:var(--ch-surface,#fff);color:var(--r);font-size:8px;font-weight:800}.dz-confirm{font-size:7px;font-weight:800}.dz-confirm input{display:block;width:180px;height:26px;border:1px solid #dce5f1;border-radius:5px;margin-top:4px;padding:4px 6px}.dz-warning{display:flex;align-items:center;gap:10px;border:1px solid var(--b);border-radius:7px;background:#fff5f5;color:#d51b24;padding:8px 12px;font-size:7px;font-weight:800}.dz-warning i{font-size:15px}@media(max-width:900px){.dz{height:auto;overflow:visible}.dz-body{grid-template-columns:1fr}.dz-nav{display:flex;overflow:auto}.dz-tab{min-width:140px}.dz-main{grid-template-rows:auto}.dz-card{grid-template-columns:50px 1fr}.dz-action{grid-column:2;margin-top:8px}}</style>
<main class="dz"><header class="dz-head"><div><p class="dz-crumb"><a href="#settings" data-sales-nav="settings">Home › Store Settings</a> › Danger Zone</p><h1>Danger Zone</h1><p class="dz-sub">Irreversible actions that can affect your store and data. Please proceed with caution.</p></div><button class="dz-save">Save Changes</button></header><div class="dz-body"><aside class="dz-nav"><a class="dz-tab" href="#settings" data-sales-nav="settings"><i class="fa fa-building-o"></i>Store Information</a><a class="dz-tab" href="#payment-billing" data-sales-nav="payment-billing"><i class="fa fa-credit-card"></i>Payment &amp; Billing</a><a class="dz-tab" href="#shipping-settings" data-sales-nav="shipping-settings"><i class="fa fa-truck"></i>Shipping Settings</a><a class="dz-tab" href="#tax-settings" data-sales-nav="tax-settings"><i class="fa fa-file-text-o"></i>Tax Settings</a><a class="dz-tab" href="#settings-notifications" data-sales-nav="settings-notifications"><i class="fa fa-bell-o"></i>Notifications</a><a class="dz-tab" href="#staff-permissions" data-sales-nav="staff-permissions"><i class="fa fa-users"></i>Staff &amp; Permissions</a><a class="dz-tab" href="#policies" data-sales-nav="policies"><i class="fa fa-shield"></i>Policies</a><a class="dz-tab danger on" href="#danger-zone" data-sales-nav="danger-zone"><i class="fa fa-trash-o"></i>Danger Zone</a></aside><section class="dz-main"><?php foreach($dangerItems as $item):?><article class="dz-card"><span class="dz-icon"><i class="fa <?=$item[0]?>"></i></span><div class="dz-copy"><h2><?=$item[1]?></h2><p><?=$item[2]?></p><ul><?php foreach($item[3] as $line):?><li><?=$line?></li><?php endforeach;?></ul></div><div class="dz-action"><button type="button"><?=$item[4]?></button><?php if($item[5]):?><label class="dz-confirm">Type <?=$item[5]?> to confirm<input aria-label="Type <?=$item[5]?> to confirm"></label><?php endif;?></div></article><?php endforeach;?><div class="dz-warning"><i class="fa fa-exclamation-triangle"></i>These actions are irreversible and can have a significant impact on your store. Please make sure you have backups of any important data.</div></section></div></main>
<?php if(!$dangerZoneEmbedded){org_page_shell_close();} ?>
