<?php
declare(strict_types=1);
require_once __DIR__.'/includes/session_org.php';
require_once __DIR__.'/includes/org_context.php';
require_once __DIR__.'/includes/org_manager_guard.php';
require_once __DIR__.'/includes/org_sales.php';
require_once __DIR__.'/../public_user/includes/org_shop.php';
require_once __DIR__.'/includes/org_ecommerce.php';
org_require_manager(); org_require_commerce_seller();
$orgId=(int)orgActiveOrgId(); $id=(int)($_GET['id']??0); $row=null;
foreach(org_sales_payout_rows($dbh,$orgId,200) as $candidate){if((int)$candidate['id']===$id){$row=$candidate;break;}}
if(!$row){header('Location: sales_management.php#payments');exit;}
if(!function_exists('h')){function h(string $s):string{return htmlspecialchars($s,ENT_QUOTES,'UTF-8');}}
$pid='PAYOUT-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);$status=strtolower((string)($row['payout_status']??'pending'));$ts=strtotime((string)($row['paid_at']?:$row['created_at']))?:time();$currency=(string)($row['currency']??'USD');$sales=(int)$row['total_cents'];$amount=(int)$row['seller_payout_cents'];$fees=max(0,$sales-$amount);$money=static fn(int $v):string=>org_sales_money($v,$currency);
$ids=array_map(static fn($r)=>(int)$r['id'],org_sales_payout_rows($dbh,$orgId,200));$pos=array_search($id,$ids,true);$prev=$pos!==false&&isset($ids[$pos-1])?$ids[$pos-1]:0;$next=$pos!==false&&isset($ids[$pos+1])?$ids[$pos+1]:0;
$pageTitle=$pid;require_once __DIR__.'/includes/org_page_shell.php';org_page_shell_open($pageTitle,'<link rel="stylesheet" href="css/commerce-hub.css?v=17"><link rel="stylesheet" href="css/sales-azia.css?v=6">');org_page_body_open('commerce-page');
?>
<style>
.pod{--t:#10204a;--m:#657292;--b:#dce5f1;color:var(--t);height:calc(100vh - var(--org-header-h,48px) - 28px);display:flex;flex-direction:column;gap:8px;overflow:hidden}.pod a{text-decoration:none}.pod-crumb{font-size:11px;font-weight:800;margin:0}.pod-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.pod h1{font-size:25px;margin:0}.pod-tag{background:#dcfce7;color:#15803d;padding:5px 9px;border-radius:7px;font-size:12px}.pod-sub{font-size:11px;color:var(--m);margin:3px 0}.pod-actions{display:flex;gap:7px}.pod-btn{height:32px;padding:0 12px;border:1px solid var(--b);background:var(--ch-surface,#fff);border-radius:8px;color:var(--t);display:inline-flex;align-items:center;font-size:11px;font-weight:800}.pod-btn.off{opacity:.4;pointer-events:none}.pod-card{border:1px solid var(--b);border-radius:10px;background:var(--ch-surface,#fff);overflow:hidden}.pod-summary{display:grid;grid-template-columns:repeat(4,1fr);padding:12px}.pod-col{padding:0 14px;border-right:1px solid var(--b)}.pod-col:last-child{border:0}.pod-stat{display:grid;grid-template-columns:29px 1fr;gap:8px;margin-bottom:9px}.pod-stat:last-child{margin:0}.pod-ico{width:29px;height:29px;border-radius:50%;background:#f3f6fb;display:flex;align-items:center;justify-content:center}.pod-lab{font-size:9px;color:var(--m)}.pod-val{font-size:11px;font-weight:800;margin-top:2px}.pod-green{color:#15803d}.pod-main{flex:1;min-height:0;display:grid;grid-template-columns:1.15fr 1fr;gap:8px}.pod-left,.pod-right{min-height:0;display:grid;gap:8px}.pod-left{grid-template-rows:1fr auto}.pod-right{grid-template-rows:1fr auto auto}.pod-sec{padding:11px 13px}.pod-sec h2{font-size:13px;margin:0 0 7px}.pod-table{width:100%;border-collapse:collapse;font-size:10px}.pod-table th,.pod-table td{padding:6px 7px;border-bottom:1px solid var(--b);text-align:left}.pod-table td:last-child,.pod-table th:last-child{text-align:right}.pod-total{background:#effaf5;color:#15734f;font-weight:900}.pod-def{display:grid;grid-template-columns:1fr 1.4fr;gap:6px 10px;font-size:10px}.pod-def span:nth-child(odd){color:var(--m)}.pod-event{display:grid;grid-template-columns:22px 1fr 1fr;gap:7px;align-items:center;font-size:9px;margin:5px 0}.pod-check{width:20px;height:20px;border-radius:50%;background:#dcfce7;color:#15803d;display:flex;align-items:center;justify-content:center}.pod-orders{display:grid;grid-template-columns:repeat(5,1fr);text-align:center;font-size:10px}.pod-orders strong{display:block;font-size:14px;margin-top:3px}.pod-doc{display:flex;justify-content:space-between;align-items:center;font-size:10px}@media(min-width:901px){html,body.org-app,body.org-app .sh-mainpanel,body.org-app .sh-pagebody{overflow:hidden!important}}@media(max-width:900px){.pod{height:auto;overflow:visible}.pod-summary,.pod-main{grid-template-columns:1fr}.pod-actions{flex-wrap:wrap}.pod-col{border:0}}
</style>
<main class="pod"><p class="pod-crumb"><a href="sales_management.php#inventory">Inventory</a> › <a href="sales_management.php#payments">Payouts</a> › <?=h($pid)?></p><div class="pod-head"><div><h1><?=h($pid)?> <span class="pod-tag"><?=h(ucfirst($status))?></span></h1><p class="pod-sub">Payout for sales earnings.</p></div><div class="pod-actions"><a class="pod-btn" href="sales_management.php#payments">← Back to Payouts</a><a class="pod-btn <?=$prev?'':'off'?>" href="<?=$prev?'payout_detail.php?id='.$prev:'#'?>">‹ Previous</a><a class="pod-btn <?=$next?'':'off'?>" href="<?=$next?'payout_detail.php?id='.$next:'#'?>">Next ›</a></div></div>
<section class="pod-card pod-summary"><div class="pod-col"><div class="pod-stat"><span class="pod-ico">⇩</span><div><div class="pod-lab">Payout ID</div><div class="pod-val" style="color:#155eef"><?=h($pid)?></div></div></div><div class="pod-stat"><span class="pod-ico"><i class="fa fa-calendar"></i></span><div><div class="pod-lab">Payout Date &amp; Time</div><div class="pod-val"><?=h(date('M j, Y g:i A',$ts))?></div></div></div><div class="pod-stat"><span class="pod-ico"><i class="fa fa-clock-o"></i></span><div><div class="pod-lab">Status</div><div class="pod-val pod-green">✓ <?=h(ucfirst($status))?></div></div></div></div><div class="pod-col"><div class="pod-stat"><span class="pod-ico"><i class="fa fa-bank"></i></span><div><div class="pod-lab">Payout Method</div><div class="pod-val">Bank Transfer</div></div></div><div class="pod-stat"><span class="pod-ico"><i class="fa fa-id-card-o"></i></span><div><div class="pod-lab">Account</div><div class="pod-val">•••• 4242</div></div></div><div class="pod-stat"><span class="pod-ico">↗</span><div><div class="pod-lab">Reference</div><div class="pod-val"><?=h((string)$row['order_code'])?></div></div></div></div><div class="pod-col"><div class="pod-stat"><span class="pod-ico"><i class="fa fa-file-text-o"></i></span><div><div class="pod-lab">Orders</div><div class="pod-val">1</div></div></div><div class="pod-stat"><span class="pod-ico"><i class="fa fa-usd"></i></span><div><div class="pod-lab">Total Sales</div><div class="pod-val"><?=h($money($sales))?></div></div></div><div class="pod-stat"><span class="pod-ico">%</span><div><div class="pod-lab">Fees &amp; Deductions</div><div class="pod-val">-<?=h($money($fees))?></div></div></div></div><div class="pod-col"><div class="pod-stat"><span class="pod-ico"><i class="fa fa-credit-card"></i></span><div><div class="pod-lab">Payout Amount</div><div class="pod-val pod-green"><?=h($money($amount))?></div></div></div><div class="pod-stat"><span class="pod-ico"><i class="fa fa-bank"></i></span><div><div class="pod-lab">Bank Name</div><div class="pod-val">Seller bank account</div></div></div><div class="pod-stat"><span class="pod-ico"><i class="fa fa-user-o"></i></span><div><div class="pod-lab">Account Name</div><div class="pod-val">Organization Seller</div></div></div></div></section>
<div class="pod-main"><div class="pod-left"><section class="pod-card pod-sec"><h2>Earnings Summary</h2><table class="pod-table"><tr><th>Description</th><th>Amount</th></tr><tr><td>Total Sales (1 Order)</td><td><?=h($money($sales))?></td></tr><tr><td>Gross Earnings</td><td><?=h($money($sales))?></td></tr><tr><td>Platform and Processing Fees</td><td>-<?=h($money($fees))?></td></tr><tr><td>Total Deductions</td><td>-<?=h($money($fees))?></td></tr><tr class="pod-total"><td>Payout Amount</td><td><?=h($money($amount))?></td></tr></table></section><section class="pod-card pod-sec"><h2>Orders Included (1)</h2><div class="pod-orders"><span>Completed<strong>1</strong></span><span>In Process<strong>0</strong></span><span>Cancelled<strong>0</strong></span><span>Refunded<strong>0</strong></span><span>Total Sales<strong><?=h($money($sales))?></strong></span></div></section></div><div class="pod-right"><section class="pod-card pod-sec"><h2>Payout Details</h2><div class="pod-def"><span>Method</span><strong>Bank Transfer</strong><span>Bank Name</span><strong>Seller bank account</strong><span>Account</span><strong>•••• 4242</strong><span>Account Type</span><strong>Business Checking</strong><span>Initiated By</span><strong>System</strong><span>Paid At</span><strong><?=h(date('M j, Y g:i A',$ts))?></strong><span>Transaction ID</span><strong><?=h((string)$row['order_code'])?></strong><span>Notes</span><strong>Payout for completed sales.</strong></div></section><section class="pod-card pod-sec"><h2>Timeline</h2><div class="pod-event"><span class="pod-check">✓</span><strong>Payout initiated</strong><span><?=h(date('M j, Y g:i A',$ts))?></span></div><div class="pod-event"><span class="pod-check">✓</span><strong>Processing</strong><span>System</span></div><div class="pod-event"><span class="pod-check">✓</span><strong>Payout completed</strong><span><?=h(ucfirst($status))?></span></div></section><section class="pod-card pod-sec"><div class="pod-doc"><div><h2>Documents</h2><span>Payout statement available from your payment provider.</span></div><button class="pod-btn" type="button" onclick="window.print()"><i class="fa fa-download"></i> Download</button></div></section></div></div></main></div><?php org_page_shell_close(); ?>
