<?php
declare(strict_types=1);
require_once __DIR__.'/includes/session_org.php'; require_once __DIR__.'/includes/org_context.php'; require_once __DIR__.'/includes/org_manager_guard.php'; require_once __DIR__.'/includes/org_sales.php';
org_require_manager(); org_require_commerce_seller(); org_ecommerce_ensure_schema($dbh);
if(!function_exists('h')){function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}}
$orgId=(int)orgActiveOrgId();$id=(int)($_GET['id']??0);$rows=org_sales_return_requests($dbh,$orgId);$r=null;foreach($rows as $x){if((int)$x['id']===$id){$r=$x;break;}}if(!$r){header('Location: sales_management.php#refunds');exit;}
$order=[];try{$st=$dbh->prepare('SELECT * FROM org_orders WHERE id=:id AND org_id=:org LIMIT 1');$st->execute([':id'=>(int)$r['order_id'],':org'=>$orgId]);$order=$st->fetch(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){}
$ref='REFUND-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);$raw=strtolower((string)$r['status']);$status=$raw==='requested'?'pending':($raw==='refunded'?'completed':$raw);$ts=strtotime((string)$r['created_at'])?:time();$currency=(string)($r['currency']??'USD');$amount=(int)($r['total_cents']??0);$money=static fn(int $v):string=>org_sales_money($v,$currency);$reason=trim((string)($r['reason']??''))?:'No reason provided';$qty=max(1,(int)($order['quantity']??1));$unit=(int)($order['unit_price_cents']??($amount/$qty));$ids=array_map(static fn($x)=>(int)$x['id'],$rows);$pos=array_search($id,$ids,true);$prev=$pos!==false&&isset($ids[$pos-1])?$ids[$pos-1]:0;$next=$pos!==false&&isset($ids[$pos+1])?$ids[$pos+1]:0;
$pageTitle=$ref;require_once __DIR__.'/includes/org_page_shell.php';org_page_shell_open($pageTitle,'<link rel="stylesheet" href="css/commerce-hub.css?v=17"><link rel="stylesheet" href="css/sales-azia.css?v=6">');org_page_body_open('commerce-page');
?>
<style>
.rd{--t:#10204a;--m:#657292;--b:#dce5f1;color:var(--t);height:calc(100vh - var(--org-header-h,48px) - 25px);display:flex;flex-direction:column;gap:8px;overflow:hidden}.rd a{text-decoration:none}.rd-crumb{font-size:11px;font-weight:800;margin:0}.rd-head{display:flex;justify-content:space-between;align-items:center}.rd h1{font-size:25px;margin:0}.rd-tag{padding:5px 9px;border-radius:7px;background:#ffedd5;color:#c2410c;font-size:11px}.rd-tag.approved,.rd-tag.completed{background:#dcfce7;color:#15803d}.rd-tag.rejected{background:#fee2e2;color:#dc2626}.rd-sub{margin:2px 0;color:var(--m);font-size:11px}.rd-actions{display:flex;gap:7px}.rd-btn{height:32px;padding:0 12px;border:1px solid var(--b);background:var(--ch-surface,#fff);border-radius:8px;color:var(--t);display:inline-flex;align-items:center;font-size:11px;font-weight:800}.rd-btn.off{opacity:.4;pointer-events:none}.rd-card{border:1px solid var(--b);border-radius:10px;background:var(--ch-surface,#fff);overflow:hidden}.rd-summary{display:grid;grid-template-columns:repeat(4,1fr);padding:12px}.rd-col{padding:0 14px;border-right:1px solid var(--b)}.rd-col:last-child{border:0}.rd-stat{display:grid;grid-template-columns:29px 1fr;gap:8px;margin-bottom:10px}.rd-stat:last-child{margin:0}.rd-ico{width:29px;height:29px;border-radius:50%;background:#f3f6fb;display:flex;align-items:center;justify-content:center}.rd-lab{font-size:9px;color:var(--m)}.rd-val{font-size:11px;font-weight:800;margin-top:2px}.rd-red{color:#ef233c}.rd-main{flex:1;min-height:0;display:grid;grid-template-columns:1.1fr 1fr;gap:8px}.rd-side{min-height:0;display:grid;grid-template-rows:1fr auto;gap:8px}.rd-sec{padding:11px 13px}.rd-sec h2{font-size:13px;margin:0 0 7px}.rd-table{width:100%;border-collapse:collapse;font-size:10px}.rd-table th,.rd-table td{padding:7px;border-bottom:1px solid var(--b);text-align:left}.rd-table td:last-child,.rd-table th:last-child{text-align:right}.rd-total{background:#fff0f0;color:#dc2626;font-weight:900}.rd-note{padding:8px;border:1px solid #cfe0ff;border-radius:7px;font-size:9px;margin-top:8px;background:#f5f8ff}.rd-event{display:grid;grid-template-columns:22px 1fr 1fr;gap:7px;align-items:center;font-size:9px;margin:8px 0}.rd-dot{width:20px;height:20px;border-radius:50%;background:#ffedd5;color:#c2410c;display:flex;align-items:center;justify-content:center}.rd-warn{background:#fff8e8;border-color:#f6ca69;color:#9a5b05}.rd-def{display:grid;grid-template-columns:1fr 1.4fr;gap:6px 10px;font-size:10px}.rd-def span:nth-child(odd){color:var(--m)}@media(min-width:901px){html,body.org-app,body.org-app .sh-mainpanel,body.org-app .sh-pagebody{overflow:hidden!important}}@media(max-width:900px){.rd{height:auto;overflow:visible}.rd-summary,.rd-main{grid-template-columns:1fr}.rd-col{border:0}}
</style>
<main class="rd"><p class="rd-crumb"><a href="sales_management.php#inventory">Inventory</a> › <a href="sales_management.php#refunds">Refunds</a> › <?=h($ref)?></p><header class="rd-head"><div><h1><?=h($ref)?> <span class="rd-tag <?=h($status)?>"><?=h(ucfirst($status))?></span></h1><p class="rd-sub">Refund issued to buyer.</p></div><div class="rd-actions"><a class="rd-btn" href="sales_management.php#refunds">← Back to Refunds</a><a class="rd-btn <?=$prev?'':'off'?>" href="<?=$prev?'refunds_detail.php?id='.$prev:'#'?>">‹ Previous</a><a class="rd-btn <?=$next?'':'off'?>" href="<?=$next?'refunds_detail.php?id='.$next:'#'?>">Next ›</a></div></header>
<section class="rd-card rd-summary">
<?php
$summary = [
  [['Refund ID',$ref],['Refund Date & Time',date('M j, Y g:i A',$ts)],['Status',ucfirst($status)]],
  [['Buyer',(string)(($r['buyer_name']??'')?:'Buyer')],['Buyer Email',(string)($r['buyer_email']??'—')],['Reason',$reason]],
  [['Refund Amount','-'.$money($amount)],['Refund Method','Original Payment Method'],['Reference','Order '.(string)$r['order_code']]],
  [['Items',$qty.' Item'.($qty===1?'':'s')],['Processed By','System'],['Notes',(string)(($r['seller_notes']??'')?:'—')]],
];
foreach($summary as $col):?><div class="rd-col"><?php foreach($col as $si=>$v):?><div class="rd-stat"><span class="rd-ico"><i class="fa <?=$si===0?'fa-info-circle':'fa-circle-o'?>"></i></span><div><div class="rd-lab"><?=h($v[0])?></div><div class="rd-val <?=$v[0]==='Refund Amount'?'rd-red':''?>"><?=h($v[1])?></div></div></div><?php endforeach;?></div><?php endforeach;?>
</section>
<div class="rd-main"><div class="rd-side"><section class="rd-card rd-sec"><h2>Refund Summary</h2><table class="rd-table"><tr><th>Description</th><th>Amount</th></tr><tr><td>Item Total</td><td><?=h($money($amount))?></td></tr><tr><td>Subtotal</td><td><?=h($money($amount))?></td></tr><tr><td>Total Deductions</td><td>$0.00</td></tr><tr class="rd-total"><td>Refund Amount</td><td>-<?=h($money($amount))?></td></tr></table><div class="rd-note">The refund will be credited using the selected refund method.</div></section><section class="rd-card rd-sec"><h2>Item(s) Refunded (<?=$qty?>)</h2><table class="rd-table"><tr><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Total</th><th>Reason</th></tr><tr><td><strong><?=h((string)($r['product_title']??'Product'))?></strong></td><td><?=$qty?></td><td><?=h($money($unit))?></td><td><?=h($money($amount))?></td><td><?=h($reason)?></td></tr></table></section></div>
<div class="rd-side"><section class="rd-card rd-sec"><h2>Timeline</h2><div class="rd-event"><span class="rd-dot">◷</span><strong>Refund initiated</strong><span><?=h(date('M j, Y g:i A',$ts))?></span></div><div class="rd-event"><span class="rd-dot">•</span><strong><?=in_array($status,['approved','completed'],true)?'Refund approved':'Awaiting review'?></strong><span>System</span></div><div class="rd-event"><span class="rd-dot"><?=$status==='completed'?'✓':'•'?></span><strong>Refund completed</strong><span><?=$status==='completed'?h(date('M j, Y g:i A',$ts)):'—'?></span></div><div class="rd-note rd-warn"><?=$status==='pending'?'This refund is pending approval.':'Current status: '.h(ucfirst($status)).'.'?></div></section><section class="rd-card rd-sec"><h2>Payment Information</h2><div class="rd-def"><span>Payment Method</span><strong><?=h((string)($order['payment_method']??'Original payment'))?></strong><span>Transaction ID</span><strong><?=h((string)$r['order_code'])?></strong><span>Refund Method</span><strong>Original Payment Method</strong><span>Order</span><strong><a href="order_details.php?id=<?=(int)$r['order_id']?>"><?=h((string)$r['order_code'])?></a></strong></div></section></div></div></main></div><?php org_page_shell_close(); ?>
