<?php
declare(strict_types=1);
require_once __DIR__.'/org_ecommerce.php';
$ssOrgId=(int)orgActiveOrgId();org_ecommerce_ensure_schema($dbh);$ssSettings=org_ecommerce_ensure_seller_info_seeded($dbh,$ssOrgId);$ssMessage='';$ssError='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['sales_settings_action']??'')==='save'){
  $ssPayload=[
    'full_name'=>trim((string)($_POST['full_name']??'')),'store_name'=>trim((string)($_POST['store_name']??'')),'tagline'=>trim((string)($_POST['tagline']??'')),
    'contact_email'=>trim((string)($_POST['contact_email']??'')),'contact_phone'=>trim((string)($_POST['contact_phone']??'')),
    'address_line1'=>trim((string)($_POST['address_line1']??'')),'address_line2'=>trim((string)($_POST['address_line2']??'')),'address_city'=>trim((string)($_POST['address_city']??'')),
    'address_state'=>trim((string)($_POST['address_state']??'')),'address_postal_code'=>trim((string)($_POST['address_postal_code']??'')),'address_country'=>trim((string)($_POST['address_country']??'')),
  ];
  $ssResult=org_ecommerce_save_seller_profile_from_post($dbh,$ssOrgId,$ssPayload);if(!empty($ssResult['ok'])){$ssMessage='Store settings saved successfully.';$ssSettings=org_ecommerce_get_shop_settings_for_display($dbh,$ssOrgId);}else{$ssError=(string)($ssResult['error']??'Could not save store settings.');}
}
$ssSettings=org_ecommerce_get_shop_settings_for_display($dbh,$ssOrgId);$ssAddr=is_array($ssSettings['address']??null)?$ssSettings['address']:[];
?>
<style>
.ss{--ink:#10204a;--muted:#687593;--line:#dce5f1;color:var(--ink);height:calc(100vh - var(--org-header-h,48px) - 34px);display:flex;flex-direction:column;gap:6px;overflow:hidden}.ss *{box-sizing:border-box}.ss-head{display:flex;justify-content:space-between;align-items:flex-start}.ss h1{font-size:22px;line-height:1.05;margin:0}.ss-crumb,.ss-sub{font-size:9px;font-weight:700;margin:0 0 2px}.ss-sub{color:var(--muted)}.ss-save{height:32px;border:0;border-radius:7px;padding:0 16px;background:#143dff;color:#fff;font-size:10px;font-weight:800}.ss-body{display:grid;grid-template-columns:180px 1fr;gap:8px;flex:1;min-height:0}.ss-nav,.ss-card{background:var(--ch-surface,#fff);border:1px solid var(--line);border-radius:9px}.ss-nav{padding:6px}.ss-tab{width:100%;height:33px;border:0;background:transparent;border-radius:7px;text-align:left;padding:0 10px;color:var(--ink);font-size:9px;font-weight:750}.ss-tab i{width:22px;font-size:13px}.ss-tab.on{background:#eef3ff;color:#143dff;border-left:2px solid #143dff}.ss-tab.danger{color:#ef233c}.ss-content{display:grid;grid-template-rows:auto auto;align-content:start;gap:7px;min-height:0}.ss-card{padding:9px 11px}.ss-info{min-height:0}.ss-card h2{font-size:13px;margin:0 0 7px}.ss-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.ss-section{border-right:1px solid var(--line);padding-right:13px}.ss-section:last-child{border:0;padding:0}.ss-section h3{font-size:11px;margin:0 0 5px}.ss-field{display:block;margin-bottom:5px;font-size:8px;font-weight:700}.ss-field input,.ss-field textarea,.ss-field select{display:block;width:100%;height:28px;margin-top:2px;border:1px solid var(--line);border-radius:6px;padding:4px 7px;color:var(--ink);font-size:9px;background:var(--ch-surface,#fff)}.ss-field textarea{height:42px;resize:none}.ss-row3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}.ss-upload{display:flex;gap:10px;align-items:center}.ss-drop{height:46px;flex:1;border:1px dashed #b8c5da;border-radius:7px;display:grid;place-items:center;color:var(--muted);font-size:8px}.ss-logo{width:46px;height:46px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;font-size:9px;font-weight:900}.ss-bottom{display:grid;grid-template-columns:1fr 1fr;gap:8px;height:150px}.ss-pref{display:flex;align-items:center;justify-content:space-between;padding:4px 2px;border-bottom:1px solid var(--line);font-size:8px}.ss-pref span small{display:block;color:var(--muted)}.ss-switch{width:28px;height:14px;border-radius:999px;background:#1748f5;position:relative}.ss-switch:after{content:'';position:absolute;width:10px;height:10px;right:2px;top:2px;background:var(--ch-surface,#fff);border-radius:50%}.ss-switch.off{background:#ccd5e4}.ss-switch.off:after{left:2px}.ss-alert{padding:6px 9px;border-radius:7px;font-size:9px;background:#dcfce7;color:#15803d}.ss-alert.err{background:#fee2e2;color:#b91c1c}
@media(min-width:1200px) and (max-height:1049px){.ss{gap:8px}.ss h1{font-size:24px}.ss-crumb,.ss-sub{font-size:10px;margin-bottom:3px}.ss-save{height:35px;font-size:11px}.ss-body{grid-template-columns:176px 1fr;gap:12px}.ss-nav{padding:7px}.ss-tab{height:40px;padding:0 12px;font-size:10px}.ss-tab i{width:25px;font-size:15px}.ss-content{grid-template-rows:465px 215px;gap:11px}.ss-card{padding:12px 16px}.ss-card h2{font-size:14px;margin-bottom:10px}.ss-info{height:auto}.ss-form-grid{gap:18px;height:calc(100% - 24px)}.ss-section{padding-right:18px}.ss-section h3{font-size:12px;margin-bottom:7px}.ss-field{font-size:9px;margin-bottom:7px}.ss-field input,.ss-field textarea,.ss-field select{height:32px;margin-top:3px;padding:6px 9px;font-size:10px}.ss-field textarea{height:52px}.ss-row3{gap:9px}.ss-upload{gap:15px}.ss-drop{height:62px;font-size:9px}.ss-logo{width:62px;height:62px;font-size:10px}.ss-bottom{height:215px;gap:11px}.ss-pref{padding:7px 3px;font-size:9px}.ss-switch{width:32px;height:18px}.ss-switch:after{width:12px;height:12px;top:3px;right:3px}.ss-switch.off:after{left:3px}}
@media(min-width:1200px) and (min-height:1050px){.ss{gap:14px;height:calc(100vh - var(--org-header-h,48px) - 24px)}.ss h1{font-size:30px}.ss-crumb,.ss-sub{font-size:13px;margin-bottom:5px}.ss-save{height:46px;padding:0 26px;font-size:14px}.ss-body{grid-template-columns:245px 1fr;gap:18px}.ss-nav{padding:10px}.ss-tab{height:56px;padding:0 17px;font-size:14px}.ss-tab i{width:34px;font-size:20px}.ss-content{gap:18px}.ss-card{padding:20px 24px}.ss-card h2{font-size:18px;margin-bottom:20px}.ss-info{height:660px}.ss-form-grid{gap:26px;height:calc(100% - 38px)}.ss-section{padding-right:26px}.ss-section h3{font-size:16px;margin-bottom:14px}.ss-field{font-size:12px;margin-bottom:14px}.ss-field input,.ss-field textarea,.ss-field select{height:44px;margin-top:7px;padding:9px 13px;font-size:13px;border-radius:7px}.ss-field textarea{height:90px}.ss-row3{gap:20px}.ss-upload{gap:34px}.ss-drop{height:105px;font-size:11px}.ss-logo{width:105px;height:105px;font-size:14px}.ss-bottom{height:318px;gap:18px}.ss-pref{padding:12px 4px;font-size:12px}.ss-pref span small{margin-top:3px}.ss-switch{width:41px;height:23px}.ss-switch:after{width:17px;height:17px;top:3px;right:3px}.ss-switch.off:after{left:3px}}
@media(min-width:901px){.ss{gap:6px;height:calc(100vh - var(--org-header-h,48px) - 34px)}.ss h1{font-size:21px}.ss-crumb,.ss-sub{font-size:8px;margin-bottom:2px}.ss-save{height:30px;padding:0 14px;font-size:9px}.ss-body{grid-template-columns:155px 1fr;gap:7px}.ss-nav{padding:5px}.ss-tab{height:31px;padding:0 8px;font-size:8px}.ss-tab i{width:20px;font-size:12px}.ss-content{grid-template-rows:minmax(0,1fr) 155px;gap:7px;height:100%;align-content:stretch}.ss-card{padding:8px 10px}.ss-card h2{font-size:11px;margin-bottom:6px}.ss-info{height:auto;min-height:0}.ss-form-grid{gap:11px;height:calc(100% - 17px)}.ss-section{padding-right:11px}.ss-section h3{font-size:9px;margin-bottom:4px}.ss-field{font-size:7px;margin-bottom:4px}.ss-field input,.ss-field textarea,.ss-field select{height:25px;margin-top:2px;padding:3px 6px;font-size:8px;border-radius:5px}.ss-field textarea{height:36px}.ss-row3{gap:5px}.ss-upload{gap:8px}.ss-drop{height:40px;font-size:7px}.ss-logo{width:40px;height:40px;font-size:8px}.ss-bottom{height:155px;gap:7px}.ss-pref{padding:3px 2px;font-size:7px}.ss-pref span small{margin-top:1px}.ss-switch{width:25px;height:13px}.ss-switch:after{width:9px;height:9px;top:2px;right:2px}.ss-switch.off:after{left:2px}}
@media(max-width:900px){.ss{height:auto;overflow:visible}.ss-body{grid-template-columns:1fr}.ss-nav{display:flex;overflow:auto}.ss-tab{min-width:150px}.ss-form-grid,.ss-bottom{grid-template-columns:1fr}.ss-bottom{height:auto}}
</style>
<form class="ss" method="post" action="sales_management.php#settings"><input type="hidden" name="sales_settings_action" value="save"><header class="ss-head"><div><p class="ss-crumb"><a href="feed.php#Home_feed">Home</a> › Store Settings</p><h1>Store Settings</h1><p class="ss-sub">Manage your store information, preferences and account settings.</p></div><button class="ss-save" type="submit">Save Changes</button></header><?php if($ssMessage):?><div class="ss-alert"><?=h($ssMessage)?></div><?php endif;?><?php if($ssError):?><div class="ss-alert err"><?=h($ssError)?></div><?php endif;?>
<div class="ss-body"><aside class="ss-nav"><button type="button" class="ss-tab on"><i class="fa fa-building-o"></i>Store Information</button><a class="ss-tab" href="#payment-billing" data-sales-nav="payment-billing" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-credit-card"></i>Payment &amp; Billing</a><a class="ss-tab" href="#shipping-settings" data-sales-nav="shipping-settings" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-truck"></i>Shipping Settings</a><a class="ss-tab" href="#tax-settings" data-sales-nav="tax-settings" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-file-text-o"></i>Tax Settings</a><a class="ss-tab" href="#settings-notifications" data-sales-nav="settings-notifications" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-bell-o"></i>Notifications</a><a class="ss-tab" href="#staff-permissions" data-sales-nav="staff-permissions" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-users"></i>Staff &amp; Permissions</a><a class="ss-tab" href="#policies" data-sales-nav="policies" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-shield"></i>Policies</a><a class="ss-tab danger" href="#danger-zone" data-sales-nav="danger-zone" style="display:flex;align-items:center;text-decoration:none"><i class="fa fa-trash-o"></i>Danger Zone</a></aside>
<div class="ss-content"><section class="ss-card ss-info"><h2>Store Information</h2><div class="ss-form-grid"><div class="ss-section"><h3>Basic Information</h3><label class="ss-field">Store Name<input required name="store_name" value="<?=h((string)($ssSettings['store_name']??''))?>"></label><label class="ss-field">Store Email<input type="email" name="contact_email" value="<?=h((string)($ssSettings['contact_email']??''))?>"></label><label class="ss-field">Phone Number<input name="contact_phone" value="<?=h((string)($ssSettings['contact_phone']??''))?>"></label><label class="ss-field">Store Description<textarea maxlength="500" name="tagline"><?=h((string)($ssSettings['tagline']??''))?></textarea></label><input type="hidden" name="full_name" value="<?=h((string)($ssSettings['full_name']??''))?>"><div class="ss-upload"><div class="ss-drop"><span><i class="fa fa-upload"></i> Click to upload logo<br>PNG or JPG, max 2MB</span></div><div class="ss-logo"><?=h(mb_strtoupper(mb_substr((string)($ssSettings['store_name']??'Store'),0,2)))?></div></div></div>
<div class="ss-section"><h3>Store Address</h3><label class="ss-field">Address Line 1<input name="address_line1" value="<?=h((string)($ssAddr['line1']??''))?>"></label><label class="ss-field">Address Line 2 (Optional)<input name="address_line2" value="<?=h((string)($ssAddr['line2']??''))?>"></label><div class="ss-row3"><label class="ss-field">City<input name="address_city" value="<?=h((string)($ssAddr['city']??''))?>"></label><label class="ss-field">State<input name="address_state" value="<?=h((string)($ssAddr['state']??''))?>"></label><label class="ss-field">ZIP Code<input name="address_postal_code" value="<?=h((string)($ssAddr['postal_code']??''))?>"></label></div><label class="ss-field">Country<input name="address_country" value="<?=h((string)($ssAddr['country']??''))?>"></label></div></div></section>
<div class="ss-bottom"><section class="ss-card"><h2>Store Preferences</h2><div class="ss-pref"><span><b>Enable Store</b><small>Your store is visible to customers.</small></span><i class="ss-switch"></i></div><div class="ss-pref"><span><b>Allow Customer Reviews</b><small>Let customers review products.</small></span><i class="ss-switch"></i></div><div class="ss-pref"><span><b>Show Out of Stock Products</b><small>Display unavailable products.</small></span><i class="ss-switch off"></i></div><div class="ss-pref"><span><b>Enable Wishlists</b><small>Allow customers to save products.</small></span><i class="ss-switch"></i></div></section><section class="ss-card"><h2>Time Zone &amp; Currency</h2><div class="ss-form-grid"><label class="ss-field">Time Zone<select><option>(GMT-06:00) Central Time (US &amp; Canada)</option></select></label><label class="ss-field">Currency<select><option>USD – US Dollar ($)</option></select></label></div></section></div></div></div></form>
