window.MSB_COMMENT_GIFS = [
  { title: 'LOL', url: 'https://i.giphy.com/media/10tIjpzIu8fe0/giphy.gif', keywords: 'laugh funny lol haha' },
  { title: 'Cat', url: 'https://i.giphy.com/media/l4FGpP4lxGGgK5CBW/giphy.gif', keywords: 'funny cat meme cute' },
  { title: 'Need it', url: 'https://i.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy.gif', keywords: 'spongebob cartoon funny' },
  { title: 'Okay', url: 'https://i.giphy.com/media/QTrG6mjkHEkpFR3DqX/giphy.gif', keywords: 'okay stitch cute cartoon' },
  { title: 'Love', url: 'https://i.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif', keywords: 'love heart cute' },
  { title: 'Wow', url: 'https://i.giphy.com/media/3kzJvEciJa94SMW3hN/giphy.gif', keywords: 'wow reaction cartoon' },
  { title: 'Thanks', url: 'https://i.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif', keywords: 'thank you appreciation' },
  { title: 'Dance', url: 'https://i.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif', keywords: 'dance happy funny' },
  { title: 'Yay', url: 'https://i.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif', keywords: 'yay flowers happy' },
  { title: 'Mind blown', url: 'https://i.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif', keywords: 'wow mind blown cartoon funny' },
  { title: 'Typing cat', url: 'https://i.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif', keywords: 'cat typing computer funny work' },
  { title: 'This is fine', url: 'https://i.giphy.com/media/NTur7Xl5fbp6/giphy.gif', keywords: 'this is fine dog fire meme' },
  { title: 'Patrick', url: 'https://i.giphy.com/media/adO3tU9inOYte/giphy.gif', keywords: 'patrick star shocked cartoon' },
  { title: 'SpongeBob', url: 'https://i.giphy.com/media/nDCjo7NKh7y3m/giphy.gif', keywords: 'spongebob cartoon funny' },
  { title: 'Homer hide', url: 'https://i.giphy.com/media/aN2Kkbz3aCc6k/giphy.gif', keywords: 'homer simpson hide bushes cartoon' },
  { title: 'Dory', url: 'https://i.giphy.com/media/11sBLFxNl7XehPQ/giphy.gif', keywords: 'dory swimming keep going cartoon' },
  { title: 'Minions', url: 'https://i.giphy.com/media/13CoX5IY9mK7m/giphy.gif', keywords: 'minions banana laugh cartoon' },
  { title: 'Grogu', url: 'https://i.giphy.com/media/gZH2aHweNmbja/giphy.gif', keywords: 'baby yoda grogu cute star wars' },
  { title: 'Popcorn', url: 'https://i.giphy.com/media/5GoVLqeAOo6PK/giphy.gif', keywords: 'popcorn watching funny' },
  { title: 'No', url: 'https://i.giphy.com/media/3oz8xKaR837dZQKKnO/giphy.gif', keywords: 'no nope shake cartoon' },
  { title: 'Yes', url: 'https://i.giphy.com/media/3o7aCTPPm4OHfRLSH6/giphy.gif', keywords: 'yes nod happy cartoon' },
  { title: 'Shrug', url: 'https://i.giphy.com/media/26BRuo6sWehM0CpjY/giphy.gif', keywords: 'shrug idk dunno cartoon' },
  { title: 'Sleepy', url: 'https://i.giphy.com/media/NfgMB8jz3nB6o/giphy.gif', keywords: 'sleep tired yawn cute' },
  { title: 'Wave', url: 'https://i.giphy.com/media/l0HlvtIPzOhhS8oFi/giphy.gif', keywords: 'wave hi hello cartoon' },
  { title: 'Clap', url: 'https://i.giphy.com/media/l0MYzxkSSjlUeA5So/giphy.gif', keywords: 'clap applause good job cartoon' },
  { title: 'Cry', url: 'https://i.giphy.com/media/d2lcHJTG5Tscg/giphy.gif', keywords: 'cry sad tears cartoon' },
  { title: 'Angry', url: 'https://i.giphy.com/media/l1J9u3TZfjmvxbtqE/giphy.gif', keywords: 'angry mad cartoon' },
  { title: 'Facepalm', url: 'https://i.giphy.com/media/XsUtdIeJ0MWMo/giphy.gif', keywords: 'facepalm oops fail cartoon' },
  { title: 'Confused', url: 'https://i.giphy.com/media/3o6Zt8MgUuvSyiHYA8/giphy.gif', keywords: 'confused huh what cartoon' },
  { title: 'Deal with it', url: 'https://i.giphy.com/media/YBso7nBfX9f1C/giphy.gif', keywords: 'deal with it cool glasses meme' },
  { title: 'Party', url: 'https://i.giphy.com/media/l0MYyO6ZHun7p4k3C/giphy.gif', keywords: 'party celebrate confetti happy' },
  { title: 'High five', url: 'https://i.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy.gif', keywords: 'high five yes team cartoon' },
  { title: 'Eye roll', url: 'https://i.giphy.com/media/3o6ZsYxFQb5gKzGZqU/giphy.gif', keywords: 'eye roll whatever annoyed' },
  { title: 'Thumbs up', url: 'https://i.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif', keywords: 'thumbs up ok good cartoon' },
  { title: 'Waiting', url: 'https://i.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif', keywords: 'waiting loading impatient' },
  { title: 'Shocked', url: 'https://i.giphy.com/media/3o6Zt6KHxJGbZRQ6zC/giphy.gif', keywords: 'shocked gasp surprise cartoon' },
  { title: 'Winking', url: 'https://i.giphy.com/media/3orieTRqhB0jACzwRO/giphy.gif', keywords: 'wink cute cartoon' },
  { title: 'Heart eyes', url: 'https://i.giphy.com/media/3o7TKr3nzbh5WgCFxe/giphy.gif', keywords: 'love heart eyes cute' },
  { title: 'Mic drop', url: 'https://i.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif', keywords: 'mic drop done boom' },
  { title: 'Slow clap', url: 'https://i.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif', keywords: 'slow clap sarcastic funny' },
  { title: 'Run', url: 'https://i.giphy.com/media/3o7TKMhGNr8nOo8nkA/giphy.gif', keywords: 'run go hurry funny' },
  { title: 'Coffee', url: 'https://i.giphy.com/media/3oEjHGr1o4GLcYZW3e/giphy.gif', keywords: 'coffee tired morning' },
  { title: 'Good luck', url: 'https://i.giphy.com/media/xT9IgG77TUjztNyD0s/giphy.gif', keywords: 'good luck fingers crossed' },
  { title: 'Hugs', url: 'https://i.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif', keywords: 'hug cute' },
  { title: 'Celebrate', url: 'https://i.giphy.com/media/26ufnwz3wKJiBMAVk/giphy.gif', keywords: 'celebrate win success' }
];
