<?php
declare(strict_types=1);
require_once __DIR__.'/includes/session_user.php'; requireUserLogin();
require_once __DIR__.'/controller.php'; require_once __DIR__.'/includes/theme_prefs.php';
if(!function_exists('h')){function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}}
$dbh=(new Controller())->pdo(); $meId=(int)($_SESSION['user_id']??0);
if(function_exists('sendNoCacheHeadersUser'))sendNoCacheHeadersUser();
if(function_exists('app_i18n_boot'))app_i18n_boot($dbh,$meId);

function community_schema(PDO $db):void{
 $db->exec("CREATE TABLE IF NOT EXISTS communities(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,owner_user_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,description TEXT NULL,category VARCHAR(80) NOT NULL DEFAULT 'General',location_name VARCHAR(160) NOT NULL DEFAULT '',privacy ENUM('public','private') NOT NULL DEFAULT 'public',join_policy ENUM('anyone','approval') NOT NULL DEFAULT 'anyone',post_permission ENUM('all','approved','staff') NOT NULL DEFAULT 'all',post_approval ENUM('immediate','approval') NOT NULL DEFAULT 'immediate',profile_image VARCHAR(500) NOT NULL DEFAULT '',cover_image VARCHAR(500) NOT NULL DEFAULT '',status TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY(owner_user_id),KEY(category,status),KEY(location_name,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $column=$db->query("SHOW COLUMNS FROM communities LIKE 'location_name'")->fetch(PDO::FETCH_ASSOC);
 if(!$column)$db->exec("ALTER TABLE communities ADD location_name VARCHAR(160) NOT NULL DEFAULT '' AFTER category, ADD KEY(location_name,status)");
 $db->exec("CREATE TABLE IF NOT EXISTS community_members(community_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,role ENUM('owner','admin','moderator','manager','member') NOT NULL DEFAULT 'member',status ENUM('active','pending','suspended','blocked') NOT NULL DEFAULT 'active',joined_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(community_id,user_id),KEY(user_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 try{$roleColumn=$db->query("SHOW COLUMNS FROM community_members LIKE 'role'")->fetch(PDO::FETCH_ASSOC);if($roleColumn&&stripos((string)($roleColumn['Type']??''),"'manager'")===false)$db->exec("ALTER TABLE community_members MODIFY role ENUM('owner','admin','moderator','manager','member') NOT NULL DEFAULT 'member'");}catch(Throwable $eRole){}
 $db->exec("CREATE TABLE IF NOT EXISTS community_rules(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,community_id BIGINT UNSIGNED NOT NULL,rule_text VARCHAR(280) NOT NULL,sort_order INT NOT NULL DEFAULT 0,KEY(community_id,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $db->exec("CREATE TABLE IF NOT EXISTS community_invitations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,community_id BIGINT UNSIGNED NOT NULL,invited_user_id BIGINT UNSIGNED NOT NULL,invited_by_user_id BIGINT UNSIGNED NOT NULL,status ENUM('pending','accepted','declined','cancelled') NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,responded_at DATETIME NULL,KEY(invited_user_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function community_image(string $field,int $uid):string{
 if(empty($_FILES[$field])||(int)($_FILES[$field]['error']??99)!==UPLOAD_ERR_OK)return'';
 $tmp=(string)$_FILES[$field]['tmp_name']; $info=@getimagesize($tmp); if(!is_uploaded_file($tmp)||$info===false)return'';
 $mime=(string)(mime_content_type($tmp)?:($info['mime']??''));$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'][$mime]??'';if($ext==='')return'';
 $dir=__DIR__.'/uploads/communities';if(!is_dir($dir))@mkdir($dir,0775,true);$name='community_'.$uid.'_'.bin2hex(random_bytes(8)).'.'.$ext;
 return @move_uploaded_file($tmp,$dir.'/'.$name)?'uploads/communities/'.$name:'';
}
try{community_schema($dbh);}catch(Throwable $e){}
if(empty($_SESSION['community_csrf']))$_SESSION['community_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['community_csrf'];$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Your session changed. Please try again.');
  $action=(string)($_POST['community_action']??'');$cid=(int)($_POST['community_id']??0);
  if($action==='create'){
   $name=mb_substr(trim((string)($_POST['name']??'')),0,150);if($name==='')throw new RuntimeException('Enter a community name.');
   $location=mb_substr(trim((string)($_POST['location_name']??'')),0,160);if($location==='')throw new RuntimeException('Enter the city and state for this community.');
   $privacy=(string)($_POST['privacy']??'')==='private'?'private':'public';$join=(string)($_POST['join_policy']??'')==='approval'?'approval':'anyone';
   $posting=in_array((string)($_POST['post_permission']??''),['all','approved','staff'],true)?(string)$_POST['post_permission']:'all';$approval=(string)($_POST['post_approval']??'')==='approval'?'approval':'immediate';
   $dbh->beginTransaction();$st=$dbh->prepare('INSERT INTO communities(owner_user_id,name,description,category,location_name,privacy,join_policy,post_permission,post_approval,profile_image,cover_image)VALUES(:o,:n,:d,:c,:l,:p,:j,:pp,:pa,:pi,:ci)');
   $st->execute([':o'=>$meId,':n'=>$name,':d'=>mb_substr(trim((string)($_POST['description']??'')),0,3000),':c'=>mb_substr(trim((string)($_POST['category']??'Local Support')),0,80),':l'=>$location,':p'=>$privacy,':j'=>$join,':pp'=>$posting,':pa'=>$approval,':pi'=>community_image('profile_image',$meId),':ci'=>community_image('cover_image',$meId)]);$cid=(int)$dbh->lastInsertId();
   $dbh->prepare("INSERT INTO community_members(community_id,user_id,role,status,joined_at,created_at,updated_at)VALUES(:c,:u,'owner','active',NOW(),NOW(),NOW())")->execute([':c'=>$cid,':u'=>$meId]);$rs=$dbh->prepare('INSERT INTO community_rules(community_id,rule_text,sort_order)VALUES(:c,:r,:s)');
   foreach(array_slice(array_values(array_filter(array_map('trim',(array)($_POST['rules']??[])))),0,10)as$i=>$rule)$rs->execute([':c'=>$cid,':r'=>mb_substr($rule,0,280),':s'=>$i]);$dbh->commit();header('Location: community.php?tab=my&created=1');exit;
  }
  if($cid<=0)throw new RuntimeException('Community not found.');
  if($action==='join'){$st=$dbh->prepare('SELECT join_policy,owner_user_id FROM communities WHERE id=:c AND status=1');$st->execute([':c'=>$cid]);$crow=$st->fetch(PDO::FETCH_ASSOC)?:[];$pending=((string)($crow['join_policy']??''))==='approval';$ownerId=(int)($crow['owner_user_id']??0);$status=$pending?'pending':'active';$joined=$pending?null:date('Y-m-d H:i:s');$dbh->prepare("INSERT INTO community_members(community_id,user_id,role,status,joined_at)VALUES(:c,:u,'member',:s,:j)ON DUPLICATE KEY UPDATE status=VALUES(status),joined_at=VALUES(joined_at)")->execute([':c'=>$cid,':u'=>$meId,':s'=>$status,':j'=>$joined]);require_once __DIR__.'/includes/community_invite_notify.php';community_notify_member_joined($dbh,$meId,$ownerId,$cid,(bool)$pending);$notice=$pending?'Your request was sent.':'You joined the community.';}
  elseif($action==='leave'){$ownerId=0;try{$stO=$dbh->prepare('SELECT owner_user_id FROM communities WHERE id=:c LIMIT 1');$stO->execute([':c'=>$cid]);$ownerId=(int)($stO->fetchColumn()?:0);}catch(Throwable $eO){}$dbh->prepare("DELETE FROM community_members WHERE community_id=:c AND user_id=:u AND role<>'owner'")->execute([':c'=>$cid,':u'=>$meId]);require_once __DIR__.'/includes/community_invite_notify.php';community_notify_member_left($dbh,$meId,$ownerId,$cid);$notice='You left the community.';}
  elseif(in_array($action,['accept_invite','decline_invite'],true)){$iid=(int)($_POST['invite_id']??0);if($iid<=0)throw new RuntimeException('Missing invitation.');$stInv=$dbh->prepare("SELECT id,community_id,invited_by_user_id FROM community_invitations WHERE id=:i AND invited_user_id=:u AND status='pending' LIMIT 1");$stInv->execute([':i'=>$iid,':u'=>$meId]);$invRow=$stInv->fetch(PDO::FETCH_ASSOC);if(!$invRow)throw new RuntimeException('Invitation not found or already answered.');$inviteCommunityId=(int)$invRow['community_id'];$inviterUserId=(int)($invRow['invited_by_user_id']??0);$accepted=$action==='accept_invite';$dbh->prepare("UPDATE community_invitations SET status=:s,responded_at=NOW() WHERE community_id=:c AND invited_user_id=:u AND status='pending'")->execute([':s'=>$accepted?'accepted':'declined',':c'=>$inviteCommunityId,':u'=>$meId]);if($accepted){$dbh->prepare("INSERT INTO community_members(community_id,user_id,role,status,joined_at)VALUES(:c,:u,'member','active',NOW())ON DUPLICATE KEY UPDATE status='active',joined_at=NOW()")->execute([':c'=>$inviteCommunityId,':u'=>$meId]);}require_once __DIR__.'/includes/community_invite_notify.php';community_notify_invite_response($dbh,$meId,$inviterUserId,$inviteCommunityId,$accepted);if($accepted){$notice='Invitation accepted. You joined the community.';header('Location: community_profile.php?id='.$inviteCommunityId);exit;}else{$notice='Invitation declined.';}}
 }catch(Throwable $e){if($dbh->inTransaction())$dbh->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Unable to update the community right now.';}
}
$tab=strtolower(trim((string)($_GET['tab']??'discover')));if(!in_array($tab,['discover','my','joined','invitations'],true))$tab='discover';$q=trim((string)($_GET['q']??''));$location=trim((string)($_GET['location']??''));$cats=['All','Emotional Support','Local Events','Church & Faith','Make New Friends','Local Advertising','Travel','Photography','Nearby Stores','Food','Education','Pets','Arts & Culture'];$category=trim((string)($_GET['category']??'All'));
$rows=[];$invites=[];$select="SELECT c.*,COALESCE(NULLIF(u.name,''),u.username,'Community Owner')owner_name,(SELECT COUNT(*)FROM community_members x WHERE x.community_id=c.id AND x.status='active')member_count,m.role my_role,m.status my_status FROM communities c JOIN users u ON u.id=c.owner_user_id LEFT JOIN community_members m ON m.community_id=c.id AND m.user_id=:me";$params=[':me'=>$meId];$where=' WHERE c.status=1';
if($tab==='discover')$where.=" AND(m.user_id IS NULL OR m.status<>'active')";elseif($tab==='my')$where.=" AND m.status='active' AND m.role IN('owner','admin','moderator','manager')";elseif($tab==='joined')$where.=" AND m.status='active' AND m.role='member'";if($q!==''){$where.=' AND(c.name LIKE :q OR c.description LIKE :q OR c.category LIKE :q)';$params[':q']='%'.$q.'%';}if($location!==''){$where.=' AND c.location_name LIKE :location';$params[':location']='%'.$location.'%';}if(strcasecmp($category,'All')!==0){$where.=' AND c.category=:cat';$params[':cat']=$category;}
try{if($tab!=='invitations'){$st=$dbh->prepare($select.$where.' ORDER BY c.updated_at DESC LIMIT 100');$st->execute($params);$rows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];}else{$focusInvite=(int)($_GET['invite']??0);$st=$dbh->prepare("SELECT i.id invite_id,c.*,(SELECT COUNT(*)FROM community_members x WHERE x.community_id=c.id AND x.status='active')member_count FROM community_invitations i JOIN communities c ON c.id=i.community_id WHERE i.invited_user_id=:me AND i.status='pending' AND c.status=1 ORDER BY i.created_at DESC");$st->execute([':me'=>$meId]);$rows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];if($focusInvite>0&&$rows){usort($rows,static function($a,$b)use($focusInvite){$aid=(int)($a['invite_id']??0)===$focusInvite?0:1;$bid=(int)($b['invite_id']??0)===$focusInvite?0:1;return $aid<=>$bid;});}}}catch(Throwable $e){}
?>
<!doctype html><html <?=function_exists('app_html_lang_attrs')?app_html_lang_attrs():'lang="en"'?>>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Communities</title><?php theme_prefs_print_head_bootstrap($dbh,$meId);?><link href="./lib/font-awesome/css/font-awesome.css" rel="stylesheet"><link href="./lib/Ionicons/css/ionicons.css" rel="stylesheet">
<style>
html,body{height:100%;margin:0}body.community-page{background:var(--msb-palette-bg,#f5f7fb);color:var(--msb-palette-text,#0f172a)}.community-app{position:fixed;inset:0 0 0 var(--feed-rail-w,72px);overflow:auto;padding:18px clamp(18px,3vw,48px) 100px;box-sizing:border-box}.community-shell{width:min(1380px,100%);margin:auto}.community-search{display:grid;grid-template-columns:1fr 1fr auto;gap:9px;width:min(850px,100%);margin:0 auto 18px}.search-field{position:relative}.search-field i{position:absolute;left:15px;top:50%;transform:translateY(-50%);color:var(--msb-palette-text-muted,#64748b)}.community-search input{width:100%;height:42px;padding:0 16px 0 42px;border:0;border-radius:9px;background:var(--msb-palette-input-bg,var(--msb-palette-surface,#fff));color:var(--msb-palette-text,#0f172a);outline:none;box-sizing:border-box}.community-search button{border:0;border-radius:9px;padding:0 18px;background:var(--msb-palette-action,#2563eb);color:var(--msb-palette-btn-text,#fff);font-weight:800}.community-head{display:flex;justify-content:space-between;gap:18px}.community-head h1{margin:0;font-size:30px}.community-head p{margin:5px 0 0;color:var(--msb-palette-text-muted,#64748b)}.community-create{align-self:flex-start;padding:11px 18px;border:0;border-radius:8px;background:var(--msb-palette-action,#2563eb);color:var(--msb-palette-btn-text,#fff);font-weight:800;cursor:pointer}.tabs,.cats{display:flex;gap:9px;overflow:auto;scrollbar-width:none}.tabs{margin:22px 0 15px;border-bottom:1px solid var(--msb-palette-border,#d0d3da)}.tabs a{padding:11px 15px;color:var(--msb-palette-text-muted,#64748b);font-weight:400 !important;text-decoration:none;white-space:nowrap;border-bottom:3px solid transparent}.tabs a.active{color:var(--msb-palette-action,#2563eb);border-color:var(--msb-palette-action,#2563eb);font-weight:400 !important}.cats{margin-bottom:18px}.cat{padding:8px 15px;border-radius:99px;background:var(--msb-palette-surface-2,var(--msb-palette-surface,#fff));color:var(--msb-palette-text,#0f172a);text-decoration:none;font-weight:700;white-space:nowrap}.cat.active{background:var(--msb-palette-action,#2563eb);color:var(--msb-palette-btn-text,#fff)}.alert{margin:12px 0;padding:11px;border-radius:8px;background:var(--msb-palette-action-soft,#dbeafe)}.alert.error{background:#fee2e2;color:#991b1b}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(196px,1fr));gap:12px;justify-content:start}
.card{
  overflow:hidden;border:1px solid #e5e7eb;border-radius:10px;background:#fff;
  box-shadow:0 1px 2px rgba(15,23,42,.04);max-width:100%;min-width:0;
  display:flex;flex-direction:column;
}
.cover{display:block;height:112px;background:linear-gradient(135deg,#2563eb,#3b82f6);background-size:cover;background-position:center;flex:0 0 auto}
.body{padding:10px 11px 11px;display:flex;flex-direction:column;gap:4px;flex:1 1 auto;min-width:0}
.title{display:block;color:#0f172a;font-size:13.5px;font-weight:800;line-height:1.25;text-decoration:none;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.meta,.desc,.location{color:#64748b;font-size:11.5px;line-height:1.35}
.location{display:block;margin-top:1px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.desc{margin:3px 0 0;height:2.7em;overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}
.actions{display:flex;gap:7px;margin-top:8px}
.actions form{flex:1;min-width:0}
.action{
  display:flex;align-items:center;justify-content:center;width:100%;min-height:32px;padding:0 10px;
  border:1px solid #e2e8f0;border-radius:8px;background:#fff;color:#334155;
  font-size:12px;font-weight:700;text-decoration:none;cursor:pointer;box-sizing:border-box;
}
.action.primary{background:#2563eb;border-color:#2563eb;color:#fff}
.action.primary:hover{background:#1d4ed8;border-color:#1d4ed8;color:#fff}
a.action.primary{
  background:#fff;border:1px solid #e2e8f0;color:#2563eb;
}
a.action.primary:hover{background:#f8fafc;border-color:#e2e8f0;color:#1d4ed8}
.action:disabled{opacity:.65;cursor:default}
.empty{
  padding:28px 18px;text-align:center;border:1px solid #e5e7eb;border-radius:8px;background:#fff;
  color:#64748b;font-size:13px;line-height:1.45;box-shadow:0 1px 2px rgba(15,23,42,.04);
}
.community-search input{
  width:100%;height:40px;padding:0 14px 0 40px;border:1px solid #e2e8f0;border-radius:8px;
  background:#fff;color:#0f172a;outline:none;box-sizing:border-box;font-size:13px;
}
.community-search input:focus{border-color:#93c5fd;box-shadow:0 0 0 3px rgba(37,99,235,.12)}
.community-search button{border:0;border-radius:8px;padding:0 16px;height:40px;background:#2563eb;color:#fff;font-weight:800;font-size:13px}
.community-create{align-self:flex-start;padding:9px 14px;border:0;border-radius:8px;background:#2563eb;color:#fff;font-weight:800;font-size:13px;cursor:pointer}
.cat{
  padding:6px 12px;border-radius:999px;border:1px solid #e2e8f0;background:#fff;color:#334155;
  text-decoration:none;font-weight:700;font-size:12px;white-space:nowrap;
}
.cat.active{background:#eff6ff;border-color:#2563eb;color:#2563eb}
.card.is-invite-focus{outline:2px solid #2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.18)}
@media(max-width:1050px){.grid{grid-template-columns:repeat(auto-fill,minmax(180px,1fr))}}
@media(max-width:800px){.grid{grid-template-columns:repeat(auto-fill,minmax(168px,1fr))}}
@media(max-width:700px){.community-app{left:0;bottom:66px;padding:14px 12px 80px}.community-search{grid-template-columns:1fr}.community-search button{height:40px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cover{height:96px}.choices{grid-template-columns:1fr}}
@media(max-width:420px){.grid{grid-template-columns:1fr}}
.modal[hidden],.pane[hidden]{display:none!important}
.modal{position:fixed;inset:0;z-index:10050;display:grid;place-items:center;padding:18px;background:rgba(2,6,23,.68)}
.dialog{width:min(680px,100%);max-height:88vh;overflow:auto;border-radius:12px;background:var(--msb-palette-bg,#f5f7fb)!important;color:var(--msb-palette-text,#0f172a)!important;border:1px solid #e5e7eb}
.dialog-head{position:sticky;top:0;display:flex;justify-content:space-between;padding:16px 18px;border-bottom:1px solid #e5e7eb;background:inherit}
.dialog-head,.pane,.wizard-actions{background:var(--msb-palette-bg,#f5f7fb);color:var(--msb-palette-text,#0f172a)}
.dialog-head h2{margin:0;font-size:18px}
.close{border:0;background:transparent;color:inherit;font-size:25px;cursor:pointer}
.steps{display:flex;gap:6px;padding:14px 18px 0}
.dot{height:5px;flex:1;border-radius:9px;background:#e2e8f0}
.dot.active{background:#2563eb}
.pane{padding:16px 18px}
.field{display:block;margin-bottom:14px}
.field>span{display:block;margin-bottom:6px;font-weight:800;font-size:13px}
.field input,.field textarea,.field select{width:100%;padding:10px 12px;border:1px solid #e2e8f0;border-radius:8px;background:#fff;color:inherit;box-sizing:border-box}
.dialog .field input,.dialog .field textarea,.dialog .field select{background:var(--msb-palette-input-bg,#fff)!important;color:var(--msb-palette-text,#0f172a)!important;border-color:#e2e8f0!important}
.dialog .field input::placeholder,.dialog .field textarea::placeholder{color:#64748b;opacity:1}
.choices{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.choices label{padding:12px;border:1px solid #e2e8f0;border-radius:8px;background:#fff}
.dialog .choices label{background:#fff;color:#0f172a}
.rules input{margin-bottom:8px}
.wizard-actions{display:flex;padding:0 18px 18px}
.wizard-actions button{padding:10px 16px;border:0;border-radius:8px;font-weight:800;cursor:pointer}
.next,.submit{margin-left:auto;background:#2563eb;color:#fff}
.invite-banner{margin:0 0 14px;padding:10px 12px;border-radius:8px;border:1px solid #bfdbfe;background:#eff6ff;color:#0f172a;font-weight:700;font-size:13px}
</style></head><body class="community-page public-page"><?php $GLOBALS['msb_skip_header_leftbar']=true;$skipHeaderThemeBootstrap=true;include __DIR__.'/includes/header.php';?>
<main class="community-app"><div class="community-shell"><form class="community-search"><input type="hidden" name="tab" value="<?=h($tab)?>"><label class="search-field"><i class="fa fa-search"></i><input name="q" value="<?=h($q)?>" placeholder="Search local communities..."></label><label class="search-field"><i class="fa fa-map-marker"></i><input name="location" value="<?=h($location)?>" placeholder="City, state — e.g. Garland, TX"></label><button type="submit">Search</button></form><header class="community-head"><div><h1>Communities</h1><p>Find local support, events, faith, friendship and useful places near you.</p></div><button class="community-create" id="openCreate" type="button"><i class="fa fa-plus"></i> Create Community</button></header>
<nav class="tabs"><?php foreach(['discover'=>'Discover','my'=>'My Communities','joined'=>'Joined','invitations'=>'Invitations']as$k=>$v):?><a class="<?=$tab===$k?'active':''?>" href="community.php?tab=<?=h($k)?>"><?=h($v)?></a><?php endforeach;?></nav>
<?php if($tab==='discover'):?><nav class="cats"><?php foreach($cats as$c):?><a class="cat<?=strcasecmp($category,$c)===0?' active':''?>" href="community.php?tab=discover&amp;category=<?=rawurlencode($c)?>&amp;location=<?=rawurlencode($location)?>"><?=h($c)?></a><?php endforeach;?></nav><?php endif;?>
<?php if((string)($_GET['created']??'')==='1'||$notice!==''):?><div class="alert"><?=h($notice!==''?$notice:'Community created. You are now its Owner.')?></div><?php endif;?><?php if($error!==''):?><div class="alert error"><?=h($error)?></div><?php endif;?><?php if($tab==='invitations'&&(int)($_GET['invite']??0)>0):?><div class="invite-banner">You have a community invitation. Accept to join, or Decline if you are not interested.</div><?php endif;?>
<?php if($rows):?><section class="grid"><?php $focusInvite=(int)($_GET['invite']??0);foreach($rows as$r):$cid=(int)$r['id'];$cover=trim((string)($r['cover_image']??''));$isFocus=$focusInvite>0&&(int)($r['invite_id']??0)===$focusInvite;?><article class="card<?=$isFocus?' is-invite-focus':''?>"<?=$isFocus?' id="community-invite-focus"':''?>><a class="cover" href="community_profile.php?id=<?=$cid?>"<?=$cover!==''?' style="background-image:url(\''.h($cover).'\')"':''?>></a><div class="body"><a class="title" href="community_profile.php?id=<?=$cid?>"><?=h((string)$r['name'])?></a><span class="meta"><?=(int)($r['member_count']??0)?> members · <?=h(ucfirst((string)$r['privacy']))?></span><span class="location"><i class="fa fa-map-marker"></i> <?=h((string)($r['location_name']??'Local community'))?></span><p class="desc"><?=h((string)($r['description']??''))?></p><div class="actions">
<?php if($tab==='discover'):?><?php if(($r['my_status']??'')==='pending'):?><button class="action" type="button" disabled>Requested</button><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="community_id" value="<?=$cid?>"><button class="action primary" name="community_action" value="join"><?=($r['join_policy']??'')==='approval'?'Request to Join':'Join'?></button></form><?php endif;?><?php elseif($tab==='invitations'):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="community_id" value="<?=$cid?>"><input type="hidden" name="invite_id" value="<?=(int)$r['invite_id']?>"><button class="action primary" name="community_action" value="accept_invite">Accept</button></form><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="community_id" value="<?=$cid?>"><input type="hidden" name="invite_id" value="<?=(int)$r['invite_id']?>"><button class="action" name="community_action" value="decline_invite">Decline</button></form><?php else:?><a class="action primary" href="community_profile.php?id=<?=$cid?>">View Community</a><?php if(($r['my_role']??'')==='member'):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="community_id" value="<?=$cid?>"><button class="action" name="community_action" value="leave">Leave</button></form><?php else:?><a class="action" href="community_profile.php?id=<?=$cid?>#manage">Manage</a><?php endif;?><?php endif;?></div></div></article><?php endforeach;?></section><?php else:?><div class="empty"><?=$tab==='discover'?'No new communities match this view yet.':($tab==='invitations'?'You have no pending community invitations.':'No communities appear here yet.')?></div><?php endif;?></div></main>
<div class="modal" id="createModal" hidden><form class="dialog" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="community_action" value="create"><header class="dialog-head"><h2>Create Community</h2><button class="close" type="button">&times;</button></header><div class="steps"><?php for($i=1;$i<=5;$i++):?><span class="dot<?=$i===1?' active':''?>"></span><?php endfor;?></div>
<section class="pane" data-step="1"><h3>Basic information</h3><label class="field"><span>Community Name</span><input name="name" maxlength="150" required placeholder="Garland Neighbors & Support"></label><label class="field"><span>City and state</span><input name="location_name" maxlength="160" required placeholder="Garland, TX"></label><label class="field"><span>Description</span><textarea name="description" rows="4" placeholder="Explain how this local community helps people connect and support one another."></textarea></label><label class="field"><span>Purpose</span><select name="category"><?php foreach(array_slice($cats,1)as$c):?><option><?=h($c)?></option><?php endforeach;?><option>Other Local Interest</option></select></label><div class="choices"><label><input type="radio" name="privacy" value="public" checked> 🌎 Public</label><label><input type="radio" name="privacy" value="private"> 🔒 Private</label></div></section>
<section class="pane" data-step="2" hidden><h3>Appearance</h3><label class="field"><span>Community profile image/logo</span><input type="file" name="profile_image" accept="image/*"></label><label class="field"><span>Cover image</span><input type="file" name="cover_image" accept="image/*"></label></section>
<section class="pane" data-step="3" hidden><h3>Membership and posting</h3><label class="field"><span>Who can join?</span><select name="join_policy"><option value="anyone">Anyone</option><option value="approval">Admin approval required</option></select></label><label class="field"><span>Who can post?</span><select name="post_permission"><option value="all">All members</option><option value="approved">Approved members</option><option value="staff">Admins/Moderators only</option></select></label><label class="field"><span>Post approval</span><select name="post_approval"><option value="immediate">Publish immediately</option><option value="approval">Require moderator approval</option></select></label></section>
<section class="pane" data-step="4" hidden><h3>Community Rules</h3><div class="rules"><?php foreach(['Be respectful','No spam','Stay on topic','No harassment','No misleading information']as$rule):?><input class="field" name="rules[]" value="<?=h($rule)?>" maxlength="280"><?php endforeach;?></div></section><section class="pane" data-step="5" hidden><h3>Preview & Create</h3><p>You will automatically become the Owner. The community will appear under My Communities.</p></section><footer class="wizard-actions"><button class="back" type="button" hidden>Back</button><button class="next" type="button">Continue</button><button class="submit" type="submit" hidden>Create Community</button></footer></form></div>
<script>(function(){var m=document.getElementById('createModal'),o=document.getElementById('openCreate'),x=m.querySelector('.close'),n=m.querySelector('.next'),b=m.querySelector('.back'),s=m.querySelector('.submit'),p=[].slice.call(m.querySelectorAll('.pane')),d=[].slice.call(m.querySelectorAll('.dot')),i=1;function paint(){p.forEach(function(e,k){e.hidden=k!==i-1});d.forEach(function(e,k){e.classList.toggle('active',k<i)});b.hidden=i===1;n.hidden=i===5;s.hidden=i!==5}o.onclick=function(){m.hidden=false;i=1;paint()};x.onclick=function(){m.hidden=true};m.onclick=function(e){if(e.target===m)m.hidden=true};n.onclick=function(){var req=p[i-1].querySelectorAll('[required]');for(var k=0;k<req.length;k++)if(!req[k].reportValidity())return;i=Math.min(5,i+1);paint()};b.onclick=function(){i=Math.max(1,i-1);paint()};document.addEventListener('keydown',function(e){if(e.key==='Escape')m.hidden=true})})();</script><script>(function(){var el=document.getElementById("community-invite-focus");if(el){try{el.scrollIntoView({behavior:"smooth",block:"center"});}catch(e){el.scrollIntoView(true);}}})();</script></body></html>
